name: Deploy Terraform Main Project

on:
  push:
    branches:
      - main

env:
  DO_TOKEN: S {{ secrets.DO_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Create and Switch the Workspace
        run: terraform workspace select tst
        #run: terraform workspace select prd

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="do_token=${{ secrets.DO_TOKEN }}"